package baitaplon.babyphoto.screen.changepass

enum class ChangePassState {
    SUCCESS, PASS_NOT_FOUND, PASS_VALID, PASS_NOT_VALID, PASS_MATCH, PASS_NOT_MATCH, PASS_NOT_NULL, PASS_NULL, UPDATE_PASS_SUCCESS, UPDATE_PASS_FAILED, GET_PASS_FAILED
}
